"""Generate docs/sample_qa.md from the REAL pipeline (nothing hand-written).   python -m scripts.make_sample_qa

The two model-written answers (concept, how-to) bypass the curated cache so the output is genuine live generation."""
import datetime as dt
import os
import sys
import time

from dotenv import load_dotenv

from rag import answer_cache
from rag.pipeline import Assistant
from rag.templates import to_text

ITEMS = [
    ("Large Cap expense ratio (both plans, from the TER file)", "What is the expense ratio of Groww Large Cap Fund (Direct)?", False),
    ("ELSS lock-in", "What is the lock-in period for Groww ELSS Tax Saver Fund?", False),
    ("Small Cap exit load (full slab from the KIM)", "What is the exit load of Groww Small Cap Fund?", False),
    ("Multicap minimum SIP (every frequency, from the KIM table)", "What is the minimum SIP of Groww Multicap Fund?", False),
    ("Concept: riskometer (retrieval + LLM)", "What is a riskometer?", True),
    ("How-to: capital-gains statement (retrieval + LLM)", "How do I download my capital-gains statement?", True),
    ("Refusal: advice", "Should I invest in Groww Small Cap?", False),
    ("Refusal: returns", "What was the 1-year return of Groww Large Cap?", False),
    ("Mixed: fact + advice", "What's ELSS's lock-in, and should I invest?", False),
    ("PII block", "My PAN is ABCDE1234F, what's my SIP status?", False),
]
SERVED = {"facts": "code template from `data/facts.json` (no model call)", "rules": "fixed template (no model call)",
          "curated": "curated answer (no model call)"}


def main():
    load_dotenv(".env")
    sys.stdout.reconfigure(encoding="utf-8")
    real_path = answer_cache.PATH
    asst = Assistant()
    asst.llm.warm()
    out = ["# Sample Q&A", "",
           f"Real outputs from the pipeline, generated by `python -m scripts.make_sample_qa` on {dt.datetime.now():%d %b %Y}. "
           "Nothing below is hand-edited. Source links and dates come from [`data/sources.csv`](../data/sources.csv).", ""]
    for n, (title, q, model) in enumerate(ITEMS, 1):
        if model:
            answer_cache.PATH = os.path.join("data", "__none__.json")      # show genuine model output, not the curated cache
            answer_cache._load.cache_clear()
        res = asst.ask(q)
        answer_cache.PATH = real_path
        answer_cache._load.cache_clear()
        r = res.response
        served = SERVED.get(res.via) or (f"retrieval + {asst.llm.last[0]} `{asst.llm.last[1]}`" if asst.llm.last else "model")
        shown_q = f"{q}  *(synthetic test value; the app hides this message and never stores or logs it)*" if r.kind == "pii_block" else q
        out += [f"## {n}. {title}", "", f"**Question:** {shown_q}", "", "**Assistant:**", ""]
        out += ["> " + line if line else ">" for line in to_text(r).split("\n")]
        out += ["", f"*Response type: `{r.kind}` · served by {served} · {res.latency_ms} ms*", ""]
        print(f"{n:2d} {r.kind:12} {res.latency_ms:5d} ms  {title}", flush=True)
        if model:
            time.sleep(15)
    open(os.path.join("docs", "sample_qa.md"), "w", encoding="utf-8").write("\n".join(out))


if __name__ == "__main__":
    main()
